### ISSUE TITLE
farmOS v3 support

### ISSUE THREAD

**Issue by paul121** [symbioquine/farm_map_google#3]
This module needs a few updates to declare support for farmOS v3 and Drupal 10. Likely just changing the `core_version_requirement` in `farm_map_google.info.yml`. The tests could be updated to use the 3.x farmOS image as well

**Comment by symbioquine** [comment]
[farm\_map\_google](https://www.drupal.org/project/farm_map_google/releases/1.0.4) is now updated to work with farmOS 3.x!
